"""Application-owned contracts implemented by infrastructure adapters."""

from netops_copilot.application.ports.device import DeviceObservationNotFound, DeviceObservationPort
from netops_copilot.application.ports.indexing import (
    DenseIndexPort,
    IndexableChunk,
    LexicalIndexPort,
)
from netops_copilot.application.ports.models import (
    EmbeddingPort,
    EmbeddingRequest,
    EmbeddingResult,
    LLMPort,
    LLMRequest,
    LLMResult,
    LocalEmbeddingPort,
    LocalLLMPort,
    ModelErrorCode,
    ModelStatus,
    RerankerPort,
    RerankRequest,
    RerankResult,
    UsageMetadata,
)
from netops_copilot.application.ports.providers import (
    Capability,
    DistanceMetric,
    EmbeddingNormalization,
    ProviderCompatibilityError,
    ProviderDescriptor,
    ProviderHealth,
    ProviderKind,
    validate_provider_compatibility,
)
from netops_copilot.application.ports.repositories import (
    IndexVersion,
    IndexVersionStatus,
    MetadataRepository,
    RepositoryNotFoundError,
)
from netops_copilot.application.ports.search import (
    DenseSearchPort,
    LexicalSearchPort,
    SearchCandidate,
    SearchChannel,
    SearchErrorCode,
    SearchFilters,
    SearchResult,
    SearchStatus,
)

__all__ = [
    "Capability",
    "DenseIndexPort",
    "DenseSearchPort",
    "DeviceObservationNotFound",
    "DeviceObservationPort",
    "DistanceMetric",
    "EmbeddingNormalization",
    "EmbeddingPort",
    "EmbeddingRequest",
    "EmbeddingResult",
    "IndexVersion",
    "IndexVersionStatus",
    "IndexableChunk",
    "LLMPort",
    "LLMRequest",
    "LLMResult",
    "LexicalIndexPort",
    "LexicalSearchPort",
    "LocalEmbeddingPort",
    "LocalLLMPort",
    "MetadataRepository",
    "ModelErrorCode",
    "ModelStatus",
    "ProviderCompatibilityError",
    "ProviderDescriptor",
    "ProviderHealth",
    "ProviderKind",
    "RepositoryNotFoundError",
    "RerankRequest",
    "RerankResult",
    "RerankerPort",
    "SearchCandidate",
    "SearchChannel",
    "SearchErrorCode",
    "SearchFilters",
    "SearchResult",
    "SearchStatus",
    "UsageMetadata",
    "validate_provider_compatibility",
]
